-- Bulk import of the initial client list. Idempotent (ON CONFLICT DO UPDATE)
-- so re-running it is safe, though prisma migrate deploy only applies it once.
INSERT INTO "Client" (id, name, "avgLoadTime", "preferredWarehouseId", "createdAt", "updatedAt") VALUES
(gen_random_uuid()::text, 'KASAI MX', 120, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'MARELLI', 60, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'MOTUS', 30, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'CT AUTOMOTIVE', 60, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'HFI', 60, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'VFM', 60, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, '910B & 220D SVMX', 30, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, '2DU ACURA RDX KASAI SVMX', 30, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'TST', 120, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'MIDORI', 120, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'TST SUMINOE', 120, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'TTM', 150, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'SRIKO', 150, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'SUMINOE TACHIS', 120, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'TESLA SVMX', 90, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'NEM DIGA', 60, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'CHIYODA', 30, NULL, now(), now()),
(gen_random_uuid()::text, 'GOTO', 60, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'YFAI', 45, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'YFS', 45, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'EISSMAN', 30, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'ASPEN', 120, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'TESLA Y AUSTIN DRX', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'HIGHLAND DRX', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'LEAR SAN LORENZO', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'LEAR LA CUESTA', 30, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'HIGHLAND COINDU', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'SVMX COMPRA VENTA', 120, (SELECT id FROM "Warehouse" WHERE code = 'N5'), now(), now()),
(gen_random_uuid()::text, 'SVMX SUBARU GZ1', 90, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'SVMX 200D', 120, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'SVMX CH2', 90, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'EVEREST YANFENG NUEVO LEON', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'EVEREST YANFENG SANTA MARIA', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'EVEREST TSTECH', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'EVEREST NYX', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'EVEREST TUOPU', 120, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'HIGHLAND YANFENG STA MARIA', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'HONDA 2GX', 30, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'SVMX TESLA HIGHLAND', 30, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'KNA', 180, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'SVMX EISSMAN', 120, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'SEIREN CONSIGNA', 150, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'TST CYBERCAB SVMX', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'SEOYON CYBERCAB', 60, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'OPAL ADIENT Y BAKING', 120, NULL, now(), now()),
(gen_random_uuid()::text, 'OPAL PISTON, PISTON S&X, Y BAKING', 150, NULL, now(), now()),
(gen_random_uuid()::text, '220D HR', 30, (SELECT id FROM "Warehouse" WHERE code = 'N4'), now(), now()),
(gen_random_uuid()::text, 'GRAMMER', 60, NULL, now(), now()),
(gen_random_uuid()::text, 'OPAL FORVIA', 120, NULL, now(), now()),
(gen_random_uuid()::text, 'WBTM', 150, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'BONDTEX', 90, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'OSHITANI', 30, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'TBA', 45, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'BRUSAROSCO', 30, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'COINDU', 30, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'MIDORI BRASIL', 90, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'BADER', 30, (SELECT id FROM "Warehouse" WHERE code = 'N2'), now(), now()),
(gen_random_uuid()::text, 'NEM TREVIÑO', 60, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now()),
(gen_random_uuid()::text, 'TOYODA GOSEI', 30, (SELECT id FROM "Warehouse" WHERE code = 'N3'), now(), now())
ON CONFLICT (name) DO UPDATE SET
  "avgLoadTime" = EXCLUDED."avgLoadTime",
  "preferredWarehouseId" = EXCLUDED."preferredWarehouseId",
  "updatedAt" = now();
